In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [69]:
df=pd.read_csv('bankloan.csv')
df=df.drop('Loan_ID',axis=1)
df=df.dropna()
df['LoanAmount']=(df['LoanAmount']*1000).astype(int)
pre_Y=df['Loan_Status']
pre_X=df.drop('Loan_Status', axis=1)

In [2]:
print(MinMaxScaler.__doc__)

Transform features by scaling each feature to a given range.

    This estimator scales and translates each feature individually such
    that it is in the given range on the training set, e.g. between
    zero and one.

    The transformation is given by::

        X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
        X_scaled = X_std * (max - min) + min

    where min, max = feature_range.

    This transformation is often used as an alternative to zero mean,
    unit variance scaling.

    Read more in the :ref:`User Guide <preprocessing_scaler>`.

    Parameters
    ----------
    feature_range : tuple (min, max), default=(0, 1)
        Desired range of transformed data.

    copy : bool, default=True
        Set to False to perform inplace row normalization and avoid a
        copy (if the input is already a numpy array).

    Attributes
    ----------
    min_ : ndarray of shape (n_features,)
        Per feature adjustment for minimum. Equivalent to
        ``min 

In [72]:
df[df['Loan_Status']=='Y']

Gender Married  Dependents     Education Self_Employed  ApplicantIncome  \
2      Male     Yes         0.0      Graduate           Yes             3000   
3      Male     Yes         0.0  Not Graduate            No             2583   
4      Male      No         0.0      Graduate            No             6000   
5      Male     Yes         2.0      Graduate           Yes             5417   
6      Male     Yes         0.0  Not Graduate            No             2333   
..      ...     ...         ...           ...           ...              ...   
608    Male     Yes         0.0      Graduate            No             3232   
609  Female      No         0.0      Graduate            No             2900   
610    Male     Yes         3.0      Graduate            No             4106   
611    Male     Yes         1.0      Graduate            No             8072   
612    Male     Yes         2.0      Graduate            No             7583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
2                  0.0       66000             360.0             1.0   
3               2358.0      120000             360.0             1.0   
4                  0.0      141000             360.0             1.0   
5               4196.0      267000             360.0             1.0   
6               1516.0       95000             360.0             1.0   
..                 ...         ...               ...             ...   
608             1950.0      108000             360.0             1.0   
609                0.0       71000             360.0             1.0   
610                0.0       40000             180.0             1.0   
611              240.0      253000             360.0             1.0   
612                0.0      187000             360.0             1.0   

    Property_Area Loan_Status  
2           Urban           Y  
3           Urban           Y  
4           Urban           Y  
5           Urban           Y  
6           Urban           Y  
..            ...         ...  
608         Rural           Y  
609         Rural           Y  
610         Rural           Y  
611         Urban           Y  
612         Urban           Y  

[332 rows x 12 columns]

In [66]:
pre_X.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area'],
      dtype='object')

In [67]:
type(pre_X[:1])

pandas.core.frame.DataFrame

In [84]:
Y=pre_Y.map(dict(Y=1,N=0))
X=pd.get_dummies(pre_X)
print(X[:5])
print(X.columns)
sc=MinMaxScaler()
X=sc.fit_transform(X)
print(X[:5])

   Dependents  ApplicantIncome  CoapplicantIncome  LoanAmount  \
1         1.0             4583             1508.0      128000   
2         0.0             3000                0.0       66000   
3         0.0             2583             2358.0      120000   
4         0.0             6000                0.0      141000   
5         2.0             5417             4196.0      267000   

   Loan_Amount_Term  Credit_History  Gender_Female  Gender_Male  Married_No  \
1             360.0             1.0              0            1           0   
2             360.0             1.0              0            1           0   
3             360.0             1.0              0            1           0   
4             360.0             1.0              0            1           1   
5             360.0             1.0              0            1           0   

   Married_Yes  Education_Graduate  Education_Not Graduate  Self_Employed_No  \
1            1                   1                    

In [74]:
X

array([[0.33333333, 0.05482993, 0.0445666 , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.03525046, 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.        , 0.03009276, 0.06968703, ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.33333333, 0.09798392, 0.00709283, ..., 0.        , 0.        ,
        1.        ],
       [0.66666667, 0.09193568, 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.        , 0.05482993, 0.        , ..., 0.        , 1.        ,
        0.        ]])

In [5]:
import joblib
mdl=joblib.load('loan_model.pkl')
ypred=mdl.predict(X)
ypred=(ypred>0.58)
ypred[:10]

array([[ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True]])

In [79]:
X

array([[0.33333333, 0.05482993, 0.0445666 , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.03525046, 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.        , 0.03009276, 0.06968703, ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.33333333, 0.09798392, 0.00709283, ..., 0.        , 0.        ,
        1.        ],
       [0.66666667, 0.09193568, 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.        , 0.05482993, 0.        , ..., 0.        , 1.        ,
        0.        ]])

In [80]:
x1=X[0].reshape((1,17))

In [81]:
x1

array([[0.33333333, 0.05482993, 0.0445666 , 0.20135364, 0.72972973,
        1.        , 0.        , 1.        , 0.        , 1.        ,
        1.        , 0.        , 1.        , 0.        , 1.        ,
        0.        , 0.        ]])

In [ ]:
sc=MinMaxScaler()
X=sc.fit_transform(X)

In [25]:
(mdl.predict(x1)>0.58)[0][0]

True

In [8]:
val=pd.DataFrame(ypred,columns=['Status'])
val=val.replace({True:'Approved', False:'Rejected'})
val[:10]

Status
0  Approved
1  Approved
2  Approved
3  Rejected
4  Approved
5  Approved
6  Rejected
7  Approved
8  Rejected
9  Approved